# Generated by Django 4.0 on 2022-02-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
