# Generated by Django 4.0 on 2022-02-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
